/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatalhaNaval: typeof import('./src/components/BatalhaNaval.vue')['default']
    Cadastro: typeof import('./src/components/Cadastro.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NovaPartida: typeof import('./src/components/novaPartida.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
